version: '3'
services:
  leed-app:
    build: leed-web
    depends_on:
      leed-database:
        condition: service_healthy
    ports:
      - "${PORT_WEB}:80"
    env_file:
      - .env
  leed-database:
    image: mysql:latest
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} < /dev/null"]
      retries: 10
    volumes: 
      - leed-db-data:/var/lib/mysql
    env_file:
      - .env 
volumes:
  leed-db-data:
